#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Run00.MvcBootstrap.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\r\n<head>\r\n\t<meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n\t<title>");

            
            #line 5 "..\..\Views\Shared\_Layout.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET MVC Application</title>\r\n\t<link");

WriteAttribute("href", Tuple.Create(" href=\"", 137), Tuple.Create("\"", 157)
, Tuple.Create(Tuple.Create("", 144), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 144), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n\t<meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n");

WriteLiteral("\t");

            
            #line 8 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t");

            
            #line 9 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n\t<header>\r\n\t\t<div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"float-left\"");

WriteLiteral(">\r\n\t\t\t\t<p");

WriteLiteral(" class=\"site-title\"");

WriteLiteral(">");

            
            #line 15 "..\..\Views\Shared\_Layout.cshtml"
                     Write(Html.ActionLink("your logo here", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" class=\"float-right\"");

WriteLiteral(">\r\n\t\t\t\t<section");

WriteLiteral(" id=\"login\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 19 "..\..\Views\Shared\_Layout.cshtml"
Write(Html.Partial("_LoginPartial"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</section>\r\n\t\t\t\t<nav>\r\n\t\t\t\t\t<ul");

WriteLiteral(" id=\"menu\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<li>");

            
            #line 23 "..\..\Views\Shared\_Layout.cshtml"
     Write(Html.ActionLink("Home", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t\t\t\t\t<li>");

            
            #line 24 "..\..\Views\Shared\_Layout.cshtml"
     Write(Html.ActionLink("About", "About", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t\t\t\t\t<li>");

            
            #line 25 "..\..\Views\Shared\_Layout.cshtml"
     Write(Html.ActionLink("Contact2", "Contact2", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t\t\t\t</ul>\r\n\t\t\t\t</nav>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</header>\r\n\t<div");

WriteLiteral(" id=\"body\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t");

            
            #line 32 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("featured", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t<section");

WriteLiteral(" class=\"content-wrapper main-content clear-fix\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t");

            
            #line 34 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t</section>\r\n\t</div>\r\n\t<footer>\r\n\t\t<div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"float-left\"");

WriteLiteral(">\r\n\t\t\t\t<p>&copy; ");

            
            #line 40 "..\..\Views\Shared\_Layout.cshtml"
         Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET MVC Application</p>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</footer>\r\n\r\n");

WriteLiteral("\t");

            
            #line 45 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t");

            
            #line 46 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
