#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Run00.MvcBootstrap.TestArea.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\n<html");

WriteLiteral(" lang=\"en\"");

WriteLiteral(">\n<head>\n\t<meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\n\t<title>");

            
            #line 5 "..\..\Views\Shared\_Layout.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET MVC Application</title>\n\t<link");

WriteAttribute("href", Tuple.Create(" href=\"", 132), Tuple.Create("\"", 152)
, Tuple.Create(Tuple.Create("", 139), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 139), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\n\t<meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\n\n");

WriteLiteral("\t");

            
            #line 9 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("\t");

            
            #line 10 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\n</head>\n<body>\n\t<header>\n\t\t<div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\n\t\t\t<div");

WriteLiteral(" class=\"float-left\"");

WriteLiteral(">\n\t\t\t\t<p");

WriteLiteral(" class=\"site-title\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Shared\_Layout.cshtml"
                     Write(Html.ActionLink("your logo here", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</p>\n\t\t\t</div>\n\t\t\t<div");

WriteLiteral(" class=\"float-right\"");

WriteLiteral(">\n\t\t\t\t<section");

WriteLiteral(" id=\"login\"");

WriteLiteral(">\n\t\t\t\t");

WriteLiteral("\n\t\t\t\t</section>\n\t\t\t\t<nav>\n\t\t\t\t\t<ul");

WriteLiteral(" id=\"menu\"");

WriteLiteral(">\n\t\t\t\t\t\t<li>");

            
            #line 24 "..\..\Views\Shared\_Layout.cshtml"
     Write(Html.ActionLink("Home", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n\t\t\t\t\t\t<li>");

            
            #line 25 "..\..\Views\Shared\_Layout.cshtml"
     Write(Html.ActionLink("About", "About", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n\t\t\t\t\t\t<li>");

            
            #line 26 "..\..\Views\Shared\_Layout.cshtml"
     Write(Html.ActionLink("Contact2", "Contact2", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\n\t\t\t\t\t</ul>\n\t\t\t\t</nav>\n\t\t\t</div>\n\t\t</div>\n\t</header>\n\t<div");

WriteLiteral(" id=\"body\"");

WriteLiteral(">\n");

WriteLiteral("\t\t");

            
            #line 33 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("featured", required: false));

            
            #line default
            #line hidden
WriteLiteral("\n\t\t<section");

WriteLiteral(" class=\"content-wrapper main-content clear-fix\"");

WriteLiteral(">\n");

WriteLiteral("\t\t\t");

            
            #line 35 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\n\t\t</section>\n\t</div>\n\t<footer>\n\t\t<div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\n\t\t\t<div");

WriteLiteral(" class=\"float-left\"");

WriteLiteral(">\n\t\t\t\t<p>&copy; ");

            
            #line 41 "..\..\Views\Shared\_Layout.cshtml"
         Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET MVC Application</p>\n\t\t\t</div>\n\t\t</div>\n\t</footer>\n\n");

WriteLiteral("\t");

            
            #line 46 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("\t");

            
            #line 47 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\n</body>\n</html>\n");

        }
    }
}
#pragma warning restore 1591
